# This file provides explicit build and function settings for Netlify.
[build]
  # This command tells Netlify how to build your frontend TypeScript code.
  # It runs the "build" script defined in your package.json.
  command = "npm run build"

  # This tells Netlify where to find your serverless functions.
  functions = "netlify/functions"
  