# This file configures how Netlify builds and deploys your site.

[build]
  # This command is run to build the site. It executes the "build" script
  # from your package.json file.
  command = "npm run build"
  
  # The directory that contains the deploy-ready assets after the build
  # command has been run. For this project, it's the root directory.
  publish = "."
  
  # The directory where your serverless functions are located.
  functions = "netlify/functions"

# Configuration for your serverless functions.
[functions]
  # This tells Netlify to use the 'esbuild' bundler for your TypeScript 
  # function. It's generally faster and works well with TypeScript.
  node_bundler = "esbuild"
